
-- ============================================
-- NYC TAXI - SNOWFLAKE INFRASTRUCTURE
-- ============================================

-- 1. Create the tool role
USE ROLE USERADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORMER
    COMMENT = 'Role for ingestion and data transformations';

-- Attach the custom role to SYSADMIN
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;


-- 2. Create the warehouse
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS NYC_TAXI_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;


-- 3. Create the database
CREATE DATABASE IF NOT EXISTS NYC_TAXI;


-- 4. Create the medallion schemas
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.RAW;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.STAGING;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.MARTS;


-- 5. Grant warehouse privileges
GRANT USAGE, OPERATE
    ON WAREHOUSE NYC_TAXI_WH
    TO ROLE TRANSFORMER;


-- 6. Grant database access
GRANT USAGE
    ON DATABASE NYC_TAXI
    TO ROLE TRANSFORMER;


-- 7. RAW schema privileges
GRANT USAGE, CREATE TABLE,
      CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA NYC_TAXI.RAW
    TO ROLE TRANSFORMER;


-- 8. STAGING schema privileges
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA NYC_TAXI.STAGING
    TO ROLE TRANSFORMER;


-- 9. INTERMEDIATE schema privileges
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA NYC_TAXI.INTERMEDIATE
    TO ROLE TRANSFORMER;


-- 10. MARTS schema privileges
GRANT USAGE, CREATE TABLE, CREATE VIEW
    ON SCHEMA NYC_TAXI.MARTS
    TO ROLE TRANSFORMER;


-- 11. Create the service user
USE ROLE USERADMIN;

CREATE USER IF NOT EXISTS AIRFLOW_SVC
    TYPE = SERVICE
    DEFAULT_ROLE = TRANSFORMER
    DEFAULT_WAREHOUSE = NYC_TAXI_WH
    DEFAULT_NAMESPACE = NYC_TAXI.RAW
    COMMENT = 'Service user for Python and Airflow';


-- 12. Assign the role to the service user
GRANT ROLE TRANSFORMER TO USER AIRFLOW_SVC;
